#!/bin/sh
test -d ~/Documents/notas || mkdir ~/Documents/notas
cd ~/Documents/notas

nombre="$1"\ 
fecha=$(date +"%y-%m-%d")

case "$1" in
	"-l") for f in *; do
			echo $f
		done
		exit 0;;

	"-o")$EDITOR "$2"; exit 0;;
	"-r")rm "$2"; exit 0;;
	"-p")nombre="$2"; fecha="";;
esac

test "$1" = "" && titulo=$fecha || titulo="$nombre"$fecha

$EDITOR "$titulo"
