#!/bin/bash
test -d ~/Documents/notas || mkdir ~/Documents/notas
cd ~/Documents/notas

nombre="$1"\ 
fecha=$(date +"%y-%m-%d")

selected=""
sel () { 
	n=0
	lista=()
	for f in *; do
		[[ "$f" == *"$2"* ]] || continue
		echo $n") "$f
		n=$(( $n + 1 ))
		lista+=("${f}")
	done
	read i
	selected="${lista[$i]}"
	test -f "$selected" || exit 1;
}


case "$1" in
	"-l") 
		for f in *; do
			echo $f
		done
		exit 0;;

	"-o")
		sel
		$EDITOR "$selected"
		exit 0;;

	"-r")sel; echo "borrar nota $selected? [y/N]"; read i; test "$i" = "y" && rm "$selected"; exit 0;;
	"-p")nombre="$2"; fecha="";;
	"-h")echo "note [NOMBRE crea una nota con nombre {yy-mm-dd NOMBRE}] [-l lista de todas las notas] [-o seleccionar una nota para abrir] [-r seleccionar una nota para borrar] [-p NOMBRE crear una nueva nota sin la fecha en el nombre]"; exit 0;;
esac

test "$1" = "" && titulo=$fecha || titulo="$nombre"$fecha

$EDITOR "$titulo"
