#!/bin/sh
directorio="~/Documents/notas"
cd $directorio

if [ $1 = "-l" ]; then
	for f in *; do
		echo $f
	done
	exit 0
fi

if [ $1 = "-o" ]; then
	$EDITOR "$2"
	exit 0
fi

if [ $1 = "-r" ]; then
	rm "$2"
	exit 0
fi

nombre="$1"\ 
fecha=$(date +"%d-%m-%y")
[ $nombre = \  ] && titulo=$fecha || titulo="$nombre"$fecha

$EDITOR "$titulo"
